<?php

namespace Milly\Laragram;

use Illuminate\Support\ServiceProvider;

class LaragramServiceProvider extends ServiceProvider
{
    public function boot ()
    {

    }

    public function register()
    {
        parent::register(); // TODO: Change the autogenerated stub
    }
}
